services:

 ethercat_senseone_container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: force_sensor
    privileged: true
    network_mode: "host"
    ipc: "host"
    pid: "host"
    environment:
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
    stdin_open: true
    tty: true
    command: bash -c "source /opt/ros/humble/setup.bash && source install/setup.bash && ros2 run senseone_eth_node senseone_eth_node enp60s0"
  